export enum OrderStatus {
  ORDER_CREATING = "ORDER_CREATING",
  ORDER_CREATION_FAILED = "ORDER_CREATION_FAILED",
  INVENTORY_PENDING = "INVENTORY_PENDING",
  INVENTORY_RESERVED = "INVENTORY_RESERVED",
  INVENTORY_REJECTED = "INVENTORY_REJECTED",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAYMENT_SUCCEEDED = "PAYMENT_SUCCEEDED",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  CANCELLED = "CANCELLED",
}
